### ISSUE TITLE
Auto-pause each time link is opened.

### ISSUE THREAD

**Issue by gasreal** [CheatBreakerNet/Client#46]
### Environment

Client

### Describe the suggestion

Implementing a toggleable auto-pause feature or removing the auto-pause altogether in Offline-Cheatbreaker would enhance the usability and flexibility of the client. The current auto-pause feature is designed to prevent users from accidentally clicking on links that may pose a security threat or harm to their computer system. However, it can be tedious and frustrating for users who need to navigate between the client and external sources frequently.

By implementing a toggleable auto-pause feature, users would have the ability to choose whether they want the game to pause when clicking on a link, providing them with greater control and flexibility over their gameplay experience. For users who are knowledgeable about internet safety and are confident in their ability to identify secure links, having the option to disable the auto-pause feature altogether would eliminate unnecessary interruptions during gameplay.

Removing the auto-pause feature or making it toggleable would not compromise the security of the software, as it is still the user's responsibility to exercise caution when clicking on links. Additionally, the feature can be overly cautious and may interrupt the gameplay experience unnecessarily, which can be frustrating for experienced users.

Overall, providing users with a toggleable auto-pause feature or removing the auto-pause altogether would enhance the usability and flexibility of the client, ultimately leading to increased user satisfaction.

### Anything else?

https://gyazo.com/afc00853d866faf7f534f7e7bf1779e8 

Example of the issue is linked above (video too big to attach).

**Comment by ShonP40** [comment]
The pause menu pops up because opening a link unfocuses the MC window. It's not to prevent users from clicking on links.
This is a normal Minecraft behavior.
