### ISSUE TITLE
Levelhead not working

### ISSUE THREAD

**Issue by aoldkawodkaw** [CheatBreakerNet/Client#49]
### Describe the bug

Levelhead doesn't show levels on Hypixel

### Steps To Reproduce

Enable levelhead in Hypixel Collection in the mods menu

### Expected Behavior

Levelhead should show levels above player heads

### Environment

```markdown
OS: Windows 10
Game version: 1.8.9
Game build number: bfa5593 
Launcher version: v2.3.6
JRE version: 8u111
```

### Anything else?

The mod is not working for me or my friend. We've tried disabling and re-enabling, relogging, restarting the client, etc., but nothing has worked so far.

The mod is enabled in this screenshot

![2023-07-25_22 44 29](https://github.com/CheatBreakerNet/Client/assets/140546089/1298cd91-04b9-4f38-9eaa-ab125d5e45a1)

**Comment by Tellinq** [comment]
Hey, can you do me a favor in the launcher:
- Go to `ADVANCED` tab
- Find **Branch** in the bottom left
- Enter **beta** and press enter

Launch 1.8.9 and verify the bottom left of the main menu shows /beta) at the end, then go on Hypixel and see if Levelhead works now

**Comment by aoldkawodkaw** [comment]
Yes, it works now. Thank you
