### ISSUE TITLE
add in text shadow

### ISSUE THREAD

**Issue by githubpub900** [CheatBreakerNet/Client#51]
### Environment

Client

### Describe the suggestion

So basiccly Lunar and Badlion etc, have this feature called text shadow as a option in fps cps keystrokes etc. and i think we need it here.

### Anything else?

![no text shadow](https://github.com/CheatBreakerNet/Client/assets/73917771/7d286079-3a44-45c5-9787-d1414036faf6)
![text shadow](https://github.com/CheatBreakerNet/Client/assets/73917771/96de0d6b-d845-4106-900a-7d179ca66e59)

the one on the top is no text shadow
the one on the bottom is text shadow

**Comment by Tellinq** [comment]
We already have this option! Please increase your customization level.
