### ISSUE TITLE
Titles Mod Bug

### ISSUE THREAD

**Issue by CyfixLMAO** [CheatBreakerNet/Client#54]
### Describe the bug

For no apparent reason, titles will shift to the right sometimes with the titles mod enabled.

### Steps To Reproduce

1. Enable titles mod
2. Play a game of bedfight (mmc)

### Expected Behavior

Some of the titles will be shifted to the left. Some games it's the victory screen, others it's the countdown timer.

### Environment

```markdown
OS: Windows 11
Game version: 1.8.9
Game build number: 
Launcher version: Latest
JRE version:
```

### Anything else?

example in game:
https://github.com/CheatBreakerNet/Client/assets/125597848/21a76f84-40fb-409a-87cb-0938c2f45935

settings of titles mod:
![2023-09-03_18 49 42](https://github.com/CheatBreakerNet/Client/assets/125597848/217fc8de-3c85-4bd0-8c5c-e846c491cf84)

**Comment by Tellinq** [comment]
This is not a bug. This is due to mod anchoring behavior

Click the Reset Mod Position button to address this
