### ISSUE TITLE
Unban

### ISSUE THREAD

**Issue by 5ohnnycode** [CheatBreakerNet/Client#60]
### Type

Client

### What is your username?

S0HNNY

### Describe the reason of your punishment (or the reason you think you were punished for)

Cheating

### Describe why we should revoke your punishment

I won't lie, at the time of the ban I was playing with an autoclick. I really ask you to cancel the punishment, since I played with him for fun, in fact, I don't play with cheats at all. I really like your client! it is very pleasant to play on it and so on. I really would not like to part with him. I agree with the punishment I received, but I ask you for a second chance, it won't happen again!

**Comment by Tellinq** [comment]
So you’re admitting to autoclicking… and yet saying you don’t cheat at all…

I hope you understand how contradictory that statement is

> I really would not like to part with [the autoclicker]

So you don’t want to stop autoclicking? That’s going to be a problem since we do not allow cheats on the client, and ban those who do use such

I’ll give you one last chance to explain yourself before I decide whether to accept or deny your appeal

**Comment by 5ohnnycode** [comment]
yes, of course, I won't use something like that

**Comment by 5ohnnycode** [comment]
I meant that I admit that I used autoclick, sorry for my English, I'm not an English speaker

> Итак, вы признаете, что используете автоклик... И все же, говоря, что вы вообще не обманываете...
> 
> Надеюсь, вы понимаете, насколько противоречиво это утверждение
> 
> > Я очень не хотелось бы расставаться с [автокликером]
> 
> Значит, вы не хотите прекращать автоклики? Это будет проблемой, так как мы не разрешаем читы на клиенте, и баним тех, кто их использует
> 
> Я дам вам последний шанс объясниться, прежде чем я решу, принять или отклонить вашу апелляцию

**Comment by 5ohnnycode** [comment]
it looks like the translator translated it wrong

**Comment by 5ohnnycode** [comment]
> Я имел в виду, что признаю, что использовал автоклик, извините за мой английский, я не англоговорящий
> 
> > Итак, вы признаете, что используете автоклик... И все же, говоря, что вы вообще не обманываете...
> > Надеюсь, вы понимаете, насколько противоречиво это утверждение
> > > Я очень не хотелось бы расставаться с [автокликером]
> > 
> > 
> > Значит, вы не хотите прекращать автоклики? Это будет проблемой, так как мы не разрешаем читы на клиенте, и баним тех, кто их использует
> > Я дам вам последний шанс объясниться, прежде чем я решу, принять или отклонить вашу апелляцию

the point is that I don't want to part with your client!

**Comment by Tellinq** [comment]
It’s alright, translators do weird stuff. I’ll accept your appeal, but don’t autoclick again, as you won’t be unbanned if you get banned

**Comment by 5ohnnycode** [comment]
thank you very much!
