### ISSUE TITLE
login bug i think

### ISSUE THREAD

**Issue by fherbb** [CheatBreakerNet/Client#61]
### Describe the bug

When i open the launcher, the option to log in appears, and when i click on it i log in with my microsoft acc. But after that nothing happens and the launcher does nothing, basically nothing changes, the log in button is there but it does nothing

### Steps To Reproduce

1. Open the launcher
2. click on log in button
3. log in with your microsoft acc
4. nothing happens (the launcher screen stays the same)

### Expected Behavior

I thought that after logging in i could start playing but as i said the launcher screen stays the same.

### Environment

```markdown
OS: macOS 13.3.1
Game version: I can't even see what version Im in
Game build number: 
Launcher version: 2.4.2
JRE version: Java 8 Update 391 i think
```

### Anything else?

<img width="1470" alt="error" src="https://github.com/CheatBreakerNet/Client/assets/153212941/6b6d6f09-1a96-41c4-9da1-399daefc89ef">

**Comment by ShonP40** [comment]
1. That’s not the JRE the launcher uses (if your launcher would’ve let you login, you’ll be able to go to the about page to see the JRE version used by the launcher)
2. Try the steps in the `Login issues` section on our [Self Diagnostics](https://cheatbreaker.net/self-diagnostics) page

**Comment by fherbb** [comment]
i tried both options of the login issues section but none of them works for this situation because my is firewall off and also the multiplayer mode is enabled.

But i tried something else

https://github.com/CheatBreakerNet/Client/assets/153212941/734fcfb3-b9a3-4c1c-9963-cc8f1e797363

**Comment by fherbb** [comment]
It didn't work 😕

**Comment by ShonP40** [comment]
Can you wait about an hour and then try to log into your account again?
Looks like you’re being rate limited by Microsoft

**Comment by fherbb** [comment]
sure

**Comment by Tellinq** [comment]
What about the official Minecraft launcher?

**Comment by Tellinq** [comment]
If that doesn’t work, then there’s nothing we can do for you. That will fall entirely on Microsoft

**Comment by fherbb** [comment]
I can log in normally  in the official minecraft launcher but if theres nothingyou can do, theres no problem. I really wanted to use CB :(

**Comment by ShonP40** [comment]
Uninstall the launcher completely using the [AppCleaner](https://freemacsoft.net/appcleaner) app, then reinstall the launcher and try to login again

**Comment by Tellinq** [comment]
Excellent! Thanks for the update.
