### ISSUE TITLE
Mouse acceleration

### ISSUE THREAD

**Issue by wfclCamelCase** [CheatBreakerNet/Client#64]
### Environment

Client

### Describe the suggestion

I'd like to suggest you adding raw input (a.k.a. no mouse acceleration) to your client like in new versions or in badlion. Since mouse acceleration is very useful for me when working with my PC I don't want to turn it off completely in the system but it messes up my aim in minecraft. I hope you consider this

**Comment by ShonP40** [comment]
Already exists

Use the client before suggesting features that already exist
