### ISSUE TITLE
launcher stuck on downloading the last update

### ISSUE THREAD

**Issue by ohasmo** [CheatBreakerNet/Client#65]
### Describe the bug

whenever there's an update, i have to delete cb, install it, then i can play

### Steps To Reproduce

open launcher when theres a new update

### Expected Behavior

to open the launcher's main screen and play minecraft

### Environment

```markdown
OS: windows 10
Game version: doesnt matter / 1.8.9
Game build number: cant get it
Launcher version: i dont know, the latest
JRE version: java 18
```

### Anything else?

![image](https://github.com/CheatBreakerNet/Client/assets/150725639/ee29f395-dff9-4424-a021-47f1dec5433b)

**Comment by ShonP40** [comment]
Read the release notes
![image](https://github.com/CheatBreakerNet/Client/assets/13995143/e351be26-4c2a-4ce2-b778-7bbc676fcc18)
