### ISSUE TITLE
Shake reduction of hit

### ISSUE THREAD

**Issue by Kydaix** [CheatBreakerNet/Client#69]
### Environment

Client

### Describe the suggestion

Hello,

I've come to make this suggestion, which I find interesting and which can be found in other PVP customers. The idea here is to allow you to customize/deactivate the intensity of the shaking when you're hit. This keeps the camera stable in combat when taking hits/damages.
It would therefore be possible to use a slider to define the intensity of the shaking, or even deactivate it altogether.

In CheatBreaker, it's possible to customize the FOV, but not the intensity. I'd love to see this addition!

Thank you for your amazin work!

**Comment by Tellinq** [comment]
We actually have this feature you’re speaking of!

in Mods, go to Hurt Cam, and then change the shake intensity of how you prefer

As a side note, what keywords are you using to search for this? I’d like to add these keywords to improve search ability

**Comment by Kydaix** [comment]
Hey, I'm really sorry, I've been looking but not enough!

In my case, I seem to have searched for "hit", "shaking", "fov".

Thanks again for your reply!
