### ISSUE TITLE
NameTag issue

### ISSUE THREAD

**Issue by R2phNow** [CheatBreakerNet/Client#70]
### Describe the bug

very little time work it did

### Steps To Reproduce

nametag show owned name

### Expected Behavior

![2024-07-13_22 33 44](https://github.com/user-attachments/assets/c900353c-3063-421c-800c-9abc6e07351c)
![2024-07-14_12 57 09](https://github.com/user-attachments/assets/f3ea46dc-abad-45c2-921b-731b5cb9df32)

### Environment

```markdown
OS: windows 10
Game version: 1.8.9
Game build number: unkown
Launcher version: 2.5.5
JRE version: 8u412
```

### Anything else?

plz add more addition for the client

**Comment by ShonP40** [comment]
Turn on the nametags mod and the self nametag option in it
