### ISSUE TITLE
please add left hand mod

### ISSUE THREAD

**Issue by dsb987** [CheatBreakerNet/Client#72]
### Environment

Client

### Describe the suggestion

please add left hand mod,thanks!
maybe someone need that...

### Anything else?

no more~

**Comment by ShonP40** [comment]
The left hand is only a thing on 1.9+, so this won't happen

**Comment by dsb987** [comment]
no ----   is there no way to transplant this feature mode...
Left handed users feel a disappointed...

**Comment by dsb987** [comment]
wait, that's not make sence... don't Raw Input be added in 1.14 ? but there still has some way to transplant it back...

**Comment by ShonP40** [comment]
Having a second hand requires all servers to implement such a feature as well since 1.7/1.8 never had the second hand packets.

On the other hand, raw mouse input is completely client side so that's not a valid comparison.

**Comment by dsb987** [comment]
wait... you may had a wrong understanding.
What I mean is that the left hand is used visually, rather than simultaneously using the left hand while using the right hand. This should be achievable. Similar 1.8forge modules already have this feature, and CMpack also has this feature.
