### ISSUE TITLE
Hit stop bug 

### ISSUE THREAD

**Issue by Equiiouh** [CheatBreakerNet/Client#74]
### Describe the bug

When im playing pvp, i click ussualy at 17 cps and sometimes randomly my sword stop by himself while im clicking so when im fighting i loose the advantage and its very disturbing my gameplay 

### Keyword search

hit stop while playing

### Solutions tried

reinstall but it doesn't change anything 

### Steps To Reproduce

i don't know the question 

### Expected Behavior

want to click normally and that won't  stop again pls help 

### Environment

```markdown
OS: 
Game version: 1.8.9
Game build number: idk 
Launcher version: idk
JRE version: idk
```

### Log file

idk

**Comment by ShonP40** [comment]
That’s a normal 1.8 thing, if you miss a hit, a penalty will be applied.

This won’t be the case on 1.7 or on 1.8 servers that enabled legacy combat through our Bukkit API.

If it’s annoying you visually, you can just adjust the swing animation in the 1.7 animations module to make it seem like it keeps swinging.

**Comment by Equiiouh** [comment]
So you are telling me that its doesn’t have any impact on m’y game its only on the visual ?Envoyé de mon iPhoneLe 13 nov. 2024 à 16:54, Shon ***@***.***> a écrit :﻿
That’s a normal 1.8 thing, if you miss a hit, a penalty will be applied.
This won’t be the case on 1.7 or on 1.8 servers that enabled legacy combat through our Bukkit API.
If it’s annoying you visually, you can just adjust the swing animation in the 1.7 animations module to make it seem like it keeps swinging.

**Comment by ShonP40** [comment]
The miss penalty does have an impact on your game.
What I said is that you can disable it visually, it’ll obviously still apply, you just won’t see it, aka it’ll look like your sword is still swinging
